### PR TITLE
Update to jQuery 3.4.1

### PR DESCRIPTION
**Pull request by puhbooh**

### CODE REVIEW

**Comment by cxj** [comment]
Looks like this fixes #62.

**Comment by axllent** [comment]
Hi guys. Is there any particular reason this has not been merged / released yet?

**Comment by iquito** [comment]
Still not merged - getting a 3.4.1 release would be great, it seems someone just needs to merge this and make a new release.

**Comment by paulirish** [comment]
I've now set the git tag for `3.4.1` as well. Thanks for everyone's patience!

**Pull request merged**
