### PR TITLE
update to jQuery 3.6.0

### PR DESCRIPTION
**Pull request by Guite**

### CODE REVIEW

**Comment by Guite** [comment]
ping @RobLoach

**Comment by Guite** [comment]
Thanks. Would you please create the release as well?

**Comment by gs-akhan** [comment]
Hi, 
You have to help me in that, also I dont think I have permissions to release this to any package manager.
I just have merge access to this repo.

**Comment by gs-akhan** [comment]
If you think, I can do anything please let me know

**Comment by Guite** [comment]
Packagist will automatically update versions based on the releases on GitHub.

If you have permission to create releases you should be able to open https://github.com/components/jquery/releases/new - here enter `3.6.0` into both `Tag version` and `Release name`. Afterwards click on `Publish release`.

**Comment by Guite** [comment]
@components/jquery anybody able to create the release?

**Comment by hawkeyetwolf** [comment]
Done! Thanks for the ping, as I don't actively watch the queue here.

**Pull request merged**
